//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChuyenDuLich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tChuyenDuLich()
        {
            this.tDangKy = new HashSet<tDangKy>();
            this.tDiaDiemThamQuan = new HashSet<tDiaDiemThamQuan>();
        }
    
        public string MaChuyen { get; set; }
        public string MaTuyen { get; set; }
        public string PhuongTien { get; set; }
        public string TenHDVien { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual tTuyen tTuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDangKy> tDangKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDiaDiemThamQuan> tDiaDiemThamQuan { get; set; }
    }
}
